name: Load Test

on:
  workflow_dispatch:

env:
  TARGET_URL: ${{ secrets.TARGET_URL }}
  USER_COUNT: ${{ secrets.USER_COUNT }}

jobs:
  loadtest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js & cache NPM
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'  # NPM cache otomatis

      - name: Cache Playwright browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            playwright-${{ runner.os }}-

      - name: Install dependencies & Playwright browsers
        run: |
          npm ci
          npx playwright install --with-deps

      - name: Run load test
        run: node index.js
